apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin

from apps import db, login_manager

from apps.authentication.util import hash_pass

class Users(db.Model, UserMixin):

    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration


class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

apps/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from importlib import import_module


db = SQLAlchemy()
login_manager = LoginManager()


def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)


def register_blueprints(app):
    for module_name in ('authentication', 'home'):
        module = import_module('apps.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)


def configure_database(app):

    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    return app

apps/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users

from apps.authentication.util import verify_pass


@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))


# Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('authentication_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template('accounts/register.html',
                               msg='User created please <a href="/login">login</a>',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login'))


# Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('home/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('home/page-500.html'), 500

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound


@blueprint.route('/index')
@login_required
def index():

    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %} 

	<!-- [ auth-signin ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="card-body">

							<img src="/static/assets/images/logo-dark.png" alt="" class="img-fluid mb-4">
							<h4 class="mb-3 f-w-400">
								Sign IN
							</h4>
							<span class="mb-0 text-muted">
								{% if msg %}
									{{ msg | safe }}
								{% else %}
									Add your credentials
								{% endif %} 
							</span>
							<!-- dummy spacer -->
							<p> <br /> </p>						
							<form role="form" method="post" action="">

								{{ form.hidden_tag() }} 
								
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="feather icon-user"></i></span>
									</div>
									{{ form.username(placeholder="Username", class="form-control") }}
								</div>
								<div class="input-group mb-4">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="feather icon-lock"></i></span>
									</div>
									{{ form.password(placeholder="Password", class="form-control", type="password") }}
								</div>
								<div class="form-group text-left mt-2">
									<div class="checkbox checkbox-primary d-inline">
										<input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
										<label for="checkbox-fill-a1" class="cr"> Save credentials</label>
									</div>
								</div>
								<button type="submit" name="login" class="btn btn-block btn-primary mb-4">Signin</button>
							
							</form>

							<p class="mb-0 text-muted">Don’t have an account? <a href="{{ url_for('authentication_blueprint.register') }}" class="f-w-400">Signup</a></p>
							<p class="mb-2 text-muted">
								<br />
								&copy; <a target="_blank" rel="noopener" href="https://bit.ly/37fF9RT" class="f-w-400">CodedThemes</a>
								- <a target="_blank" rel="noopener" 
								     href="https://appseed.us/admin-dashboards/flask-dashboard-gradientable" class="f-w-400">Flask Gradient</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signin ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

	<script src="/static/assets/js/waves.min.js"></script>

{% endblock javascripts %} 

apps/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %}

{% block content %} 

	<!-- [ auth-signup ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="card-body">
							<img src="/static/assets/images/logo-dark.png" alt="" class="img-fluid mb-4">
							<h4 class="mb-3 f-w-400">
								Sign UP
							</h4>
							<span class="mb-0 text-muted">
								{% if msg %}
									{{ msg | safe }}
								{% else %}
									Add your credentials
								{% endif %} 
							</span>
							<!-- dummy spacer -->
							<p> <br /> </p>		
							
							<!-- Hide the form on success -->
							{% if not success %}
								<form role="form" method="post" action="">

									{{ form.hidden_tag() }}  
															
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text"><i class="feather icon-user"></i></span>
										</div>
										{{ form.username(placeholder="Username", class="form-control") }}
									</div>
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text"><i class="feather icon-mail"></i></span>
										</div>
										{{ form.email(placeholder="Email", class="input form-control", type="email") }}
									</div>
									<div class="input-group mb-4">
										<div class="input-group-prepend">
											<span class="input-group-text"><i class="feather icon-lock"></i></span>
										</div>
										{{ form.password(placeholder="Password", class="form-control", type="password") }}
									</div>
									<div class="form-group text-left mt-2">
										<div class="checkbox checkbox-primary d-inline">
											<input type="checkbox" name="checkbox-fill-2" id="checkbox-fill-2">
											<label for="checkbox-fill-2" class="cr">I agree with <a href="#">terms</a>.</label>
										</div>
									</div>
									<button type="submit" name="register" class="btn btn-primary btn-block mb-4">Sign up</button>
								
								</form>

								<p class="mb-0 text-muted">Have an account? <a href="{{ url_for('authentication_blueprint.login') }}" class="f-w-400">Login</a></p>
							{% endif %}

							<p class="mb-2 text-muted">
								<br />
								&copy; <a target="_blank" rel="noopener" href="https://bit.ly/37fF9RT" class="f-w-400">CodedThemes</a>
								- <a target="_blank" rel="noopener" 
								     href="https://appseed.us/admin-dashboards/flask-dashboard-gradientable" class="f-w-400">Flask Gradient</a>
							</p>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signup ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

	<script src="/static/assets/js/waves.min.js"></script>

{% endblock javascripts %} 

apps/templates/home/auth-signin.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign IN {% endblock %}

{% block content %} 

	<!-- [ auth-signin ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="card-body">
							<img src="/static/assets/images/logo-dark.png" alt="" class="img-fluid mb-4">
							<h4 class="mb-3 f-w-400">Signin</h4>
							<div class="input-group mb-3">
								<div class="input-group-prepend">
									<span class="input-group-text"><i class="feather icon-mail"></i></span>
								</div>
								<input type="email" class="form-control" placeholder="Email address">
							</div>
							<div class="input-group mb-4">
								<div class="input-group-prepend">
									<span class="input-group-text"><i class="feather icon-lock"></i></span>
								</div>
								<input type="password" class="form-control" placeholder="Password">
							</div>
							<div class="form-group text-left mt-2">
								<div class="checkbox checkbox-primary d-inline">
									<input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
									<label for="checkbox-fill-a1" class="cr"> Save credentials</label>
								</div>
							</div>
							<button class="btn btn-block btn-primary mb-4">Signin</button>
							<p class="mb-2 text-muted">Forgot password? <a href="auth-reset-password.html" class="f-w-400">Reset</a></p>
							<p class="mb-0 text-muted">Don’t have an account? <a href="auth-signup.html" class="f-w-400">Signup</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signin ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

	<script src="/static/assets/js/waves.min.js"></script>

{% endblock javascripts %} 

apps/templates/home/bc_tooltip-popover.html
{% extends "layouts/base.html" %}

{% block title %} UI Tooltip {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}		

	<!-- [ Main Content ] start -->
	<div class="pcoded-main-container">
		<div class="pcoded-content">
			<!-- [ breadcrumb ] start -->
			<div class="page-header">
				<div class="page-block">
					<div class="row align-items-center">
						<div class="col-md-12">
							<div class="page-header-title">
								<h5 class="m-b-10">Tooltip &amp; Popover</h5>
							</div>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
								<li class="breadcrumb-item"><a href="#!">Basic Components</a></li>
								<li class="breadcrumb-item"><a href="#!">Tooltip &amp; Popover</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- [ breadcrumb ] end -->
			<!-- [ Main Content ] start -->
			<div class="row">
				<!-- [ tooltip ] start -->
				<div class="col-md-6 col-sm-12">
					<div class="card">
						<div class="card-header">
							<h5>Tooltip</h5>
						</div>
						<div class="card-body btn-page">
							<button type="button" class="btn  btn-danger" data-toggle="tooltip" data-placement="top" title="tooltip on top">Top</button>
							<button type="button" class="btn  btn-primary" data-toggle="tooltip" data-placement="left" title="tooltip on left">Left</button>
							<button type="button" class="btn  btn-success" data-toggle="tooltip" data-placement="right" title="tooltip on right">Right</button>
							<button type="button" class="btn  btn-warning" data-toggle="tooltip" data-placement="bottom" title="tooltip on bottom">Bottom</button>
							<button type="button" class="btn  btn-info" data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">Html Tooltip</button>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-sm-12">
					<div class="card">
						<div class="card-header">
							<h5>Popover</h5>
						</div>
						<div class="card-body btn-page">
							<button type="button" class="btn  btn-danger" data-toggle="popover" data-placement="top" title="" data-content="top by popover" data-original-title="popup on top">Top</button>
							<button type="button" class="btn  btn-primary" data-toggle="popover" data-placement="left" title="popup on left" data-content="left by popover">Left</button>
							<button type="button" class="btn  btn-success" data-toggle="popover" data-placement="right" title="popup on right" data-content="right by popover">Right</button>
							<button type="button" class="btn  btn-warning" data-toggle="popover" data-placement="bottom" title="popup on bottom" data-content="bottom by popover">Bottom</button>
							<button type="button" class="btn  btn-info" data-toggle="popover" data-html="true" data-placement="top" title="<em>popup</em> <u>with</u> <b>HTML</b>" data-content="popup by HTML">Html popup</button>
						</div>
					</div>
				</div>
				<!-- [ tooltip ] end -->
			</div>
		</div>
	</div>
	<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/includes/navigation.html
	<!-- [ Header ] start -->
	<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-blue">
		
			
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
            <a href="#!" class="b-brand">
                <!-- ========   change your logo hear   ============ -->
                <img src="/static/assets/images/logo.png" alt="" class="logo">
                <img src="/static/assets/images/logo-icon.png" alt="" class="logo-thumb">
            </a>
            <a href="#!" class="mob-toggler">
                <i class="feather icon-more-vertical"></i>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#!" class="pop-search"><i class="feather icon-search"></i></a>
                    <div class="search-bar">
                        <input type="text" class="form-control border-0 shadow-none" placeholder="Search here">
                        <button type="button" class="close" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="#!" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li>
                    <div class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown"><i class="icon feather icon-bell"></i><span class="badge bg-danger"><span class="sr-only"></span></span></a>
                        <div class="dropdown-menu dropdown-menu-right notification">
                            <div class="noti-head">
                                <h6 class="d-inline-block m-b-0">Notifications</h6>
                                <div class="float-right">
                                    <a href="#!" class="m-r-10">mark as read</a>
                                    <a href="#!">clear all</a>
                                </div>
                            </div>
                            <ul class="noti-body">
                                <li class="n-title">
                                    <p class="m-b-0">NEW</p>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>John Doe</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>5 min</span></p>
                                            <p>New ticket Added</p>
                                        </div>
                                    </div>
                                </li>
                                <li class="n-title">
                                    <p class="m-b-0">EARLIER</p>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>10 min</span></p>
                                            <p>Prchace New Theme and make payment</p>
                                        </div>
                                    </div>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>12 min</span></p>
                                            <p>currently login</p>
                                        </div>
                                    </div>
                                </li>
                                <li class="notification">
                                    <div class="media">
                                        <img class="img-radius" src="/static/assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                            <p>Prchace New Theme and make payment</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <div class="noti-footer">
                                <a href="#!">show all</a>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropdown drp-user">
                        <a href="#!" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius wid-40" alt="User-Profile-Image">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-notification">
                            <div class="pro-head">
                                <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image">
                                <span>
                                    {{ current_user.username }}
                                </span>
                                <a href="{{ url_for('authentication_blueprint.logout') }}" class="dud-logout" title="Logout">
                                    <i class="feather icon-log-out"></i>
                                </a>
                            </div>
                            <ul class="pro-body">
                                <li><a href="#" class="dropdown-item"><i class="feather icon-user"></i> Profile - {{ current_user.username }} </a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        
    
    </header>
    <!-- [ Header ] end -->

apps/templates/includes/scripts.html
    <script src="/static/assets/js/vendor-all.min.js"></script>
    <script src="/static/assets/js/plugins/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.min.js"></script>

apps/templates/includes/sidebar.html
	<!-- [ navigation menu ] start -->
	<nav class="pcoded-navbar menupos-fixed menu-light ">
		<div class="navbar-wrapper  ">
			<div class="navbar-content scroll-div " >
				<ul class="nav pcoded-inner-navbar ">
					<li class="nav-item pcoded-menu-caption">
						<label>Navigation</label>
					</li>
					<li class="nav-item">
					    <a href="/" class="nav-link ">
                            <span class="pcoded-micon">
                                <i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span></a>
					</li>
					<li class="nav-item pcoded-hasmenu">
					    <a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-layout"></i></span><span class="pcoded-mtext">Page layouts</span></a>
					    <ul class="pcoded-submenu">
					        <li><a href="/layout-vertical.html">Vertical</a></li>
					        <li><a href="/layout-horizontal.html">Horizontal</a></li>
					    </ul>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>UI Element</label>
					</li>
					<li class="nav-item pcoded-hasmenu">
						<a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span class="pcoded-mtext">Basic</span></a>
						<ul class="pcoded-submenu">
							<li><a href="/bc_alert.html">Alert</a></li>
							<li><a href="/bc_button.html">Button</a></li>
							<li><a href="/bc_badges.html">Badges</a></li>
							<li><a href="/bc_breadcrumb-pagination.html">Pagination</a></li>
							<li><a href="/bc_card.html">Cards</a></li>
							<li><a href="/bc_collapse.html">Collapse</a></li>
							<li><a href="/bc_carousel.html">Carousel</a></li>
							<li><a href="/bc_grid.html">Grid system</a></li>
							<li><a href="/bc_progress.html">Progress</a></li>
							<li><a href="/bc_modal.html">Modal</a></li>
							<li><a href="/bc_spinner.html">Spinner</a></li>
							<li><a href="/bc_tabs.html">Tabs & pills</a></li>
							<li><a href="/bc_typography.html">Typography</a></li>
							<li><a href="/bc_tooltip-popover.html">Tooltip & popovers</a></li>
							<li><a href="/bc_toasts.html">Toasts</a></li>
							<li><a href="/bc_extra.html">Other</a></li>
						</ul>
					</li>
					<li class="nav-item pcoded-menu-caption">
					    <label>Forms &amp; table</label>
					</li>
					<li class="nav-item">
					    <a href="/form_elements.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-file-text"></i></span><span class="pcoded-mtext">Forms</span></a>
					</li>
					<li class="nav-item">
					    <a href="/tbl_bootstrap.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-align-justify"></i></span><span class="pcoded-mtext">Bootstrap table</span></a>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>Chart & Maps</label>
					</li>
					<li class="nav-item">
					    <a href="/chart-apex.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a>
					</li>
					<li class="nav-item">
					    <a href="/map-google.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-map"></i></span><span class="pcoded-mtext">Maps</span></a>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>Pages</label>
					</li>
					<li class="nav-item pcoded-hasmenu">
					    <a href="#!" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span class="pcoded-mtext">Authentication</span></a>
					    <ul class="pcoded-submenu">
					        <li><a href="/auth-signup.html">Sign up (template)</a></li>
					        <li><a href="/auth-signin.html">Sign in (template)</a></li>
					    </ul>
					</li>
					<li class="nav-item"><a href="/sample-page.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a></li>

					<li class="nav-item pcoded-menu-caption">
						<label>Action zone</label>
					</li>
					<li class="nav-item">
					    <a href="{{ url_for('authentication_blueprint.logout') }}" 
						   class="nav-link "><span class="pcoded-micon">
						   <i class="feather icon-log-out"></i></span><span class="pcoded-mtext">Logout</span></a>
					</li>
					<li class="nav-item">
					    <a target="_blank" rel="noopener" href="https://appseed.us/support" 
						   class="nav-link "><span class="pcoded-micon">
						   <i class="feather icon-info"></i></span><span class="pcoded-mtext">Support</span></a>
					</li>

				</ul>
				
				<div class="card text-center">
					<div class="card-block">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <i class="feather icon-sunset f-40"></i>
                        <br />
						<p>Need more?</p>
						<a target="_blank" rel="noopener noreferrer" 
						   href="https://appseed.us/admin-dashboards/flask-dashboard-gradient-pro"
                           class="btn btn-primary btn-sm text-white m-0">Gradient PRO</a>
					</div>
				</div>
				
			</div>
		</div>
	</nav>
    <!-- [ navigation menu ] end -->